#.travis.yml

sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - 8.14.0

before_script:
  - set -e
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g --silent firebase-tools @angular/cli typescript tslint
  - npm install --build-from-source

script:
  - npm run lint
  - npm run test:ci
  - npm run e2e
  - npm run build:ci

deploy:
  - provider: firebase
    skip_cleanup: true
    token:
      secure: $FIREBASE_TOKEN
    project: poll-wizard
    on:
      branch: master
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist/poll-wizard
    on:
      branch: master

notifications:
  email:
    on_failure: change
    on_success: change
